name: AcceptRules
version: 1.7.1
main: nz.net.mcewan.AcceptRulesMain
permissions:
    acceptrules.settp:
        description: /acceptrules settp
        default: op
    acceptrules.notifyonaccept:
        description: sends message when someone accepts rules!
        default: false
commands:
  acceptrules:
    description: Used to accept rules!
    usage: /acceptrules